
__all__ = ['COLOR_BGR2GRAY','COLORMAP_AUTUMN','COLORMAP_BONE','COLORMAP_CIVIDIS','COLORMAP_COOL',
'COLORMAP_DEEPGREEN','COLORMAP_HOT','COLORMAP_HSV','COLORMAP_INFERNO','COLORMAP_JET','COLORMAP_MAGMA',
'COLORMAP_OCEAN','COLORMAP_PARULA','COLORMAP_PINK','COLORMAP_PLASMA','COLORMAP_RAINBOW',
'COLORMAP_SPRING','COLORMAP_TURBO','COLORMAP_TWILIGHT','COLORMAP_TWILIGHT_SHIFTED','COLORMAP_VIRIDIS',
'COLORMAP_WINTER']


COLOR_BGR2BGR555 = 'COLOR_BGR2BGR555'
COLOR_BGR2BGR565 = "COLOR_BGR2BGR565"
COLOR_BGR2BGRA = "COLOR_BGR2BGRA"
COLOR_BGR2GRAY = 'COLOR_BGR2GRAY'


COLOR_BAYER_BG2BGR = 'COLOR_BAYER_BG2BGR'
COLOR_BAYER_BG2BGR_EA = "COLOR_BAYER_BG2BGR_EA"
COLOR_BAYER_BG2BGR_VNG = "COLOR_BAYER_BG2BGR_VNG"
COLOR_BAYER_BG2BGRA = "COLOR_BAYER_BG2BGRA"
COLOR_BAYER_BG2BGRAY = "COLOR_BAYER_BG2BGRAY"

COLOR_BAYER_BG2RGB = "COLOR_BAYER_BG2RGB"
COLOR_BAYER_BG2RGB_EA = "COLOR_BAYER_BG2RGB_EA"
COLOR_BAYER_BG2RGB_VNG = "COLOR_BAYER_BG2RGB_VNG"
COLOR_BAYER_BG2RGBA = "COLOR_BAYER_BG2RGBA"
COLOR_BAYER_BGGR2BGR = "COLOR_BAYER_BGGR2BGR"


COLOR_BAYER_BGGR2BGR_EA = "COLOR_BAYER_BGGR2BGR_EA"
COLOR_BAYER_BGGR2BGR_VNG = "COLOR_BAYER_BGGR2BGR_VNG"
COLOR_BAYER_BGGR2BGRA = "COLOR_BAYER_BGGR2BGRA"
COLOR_BAYER_BGGR2GRAY = "COLOR_BAYER_BGGR2GRAY"
COLOR_BAYER_BGGR2RGB = "COLOR_BAYER_BGGR2RGB"

COLOR_BAYER_BGGR2RGB_EA = "COLOR_BAYER_BGGR2RGB_EA"
COLOR_BAYER_BGGR2RGB_VNG = "COLOR_BAYER_BGGR2RGB_VNG"
COLOR_BAYER_BGGR2RGBA = "COLOR_BAYER_BGGR2RGBA"
COLOR_BAYER_GB2BGR = "COLOR_BAYER_GB2BGR"
COLOR_BAYER_GB2BGR_EA = "COLOR_BAYER_GB2BGR_EA"






























COLORMAP_AUTUMN = "COLORMAP_AUTUMN"
COLORMAP_BONE = "COLORMAP_BONE"
COLORMAP_CIVIDIS = "COLORMAP_CIVIDIS"
COLORMAP_COOL = "COLORMAP_COOL"
COLORMAP_DEEPGREEN = "COLORMAP_DEEPGREEN"
COLORMAP_HOT = "COLORMAP_HOT"
COLORMAP_HSV = "COLORMAP_HSV"
COLORMAP_INFERNO = "COLORMAP_INFERNO"
COLORMAP_JET = "COLORMAP_JET"
COLORMAP_MAGMA = "COLORMAP_MAGMA"
COLORMAP_OCEAN = "COLORMAP_OCEAN"
COLORMAP_PARULA = "COLORMAP_PARULA"
COLORMAP_PINK = "COLORMAP_PINK"
COLORMAP_PLASMA = "COLORMAP_PLASMA"
COLORMAP_RAINBOW = "COLORMAP_RAINBOW"
COLORMAP_SPRING = "COLORMAP_SPRING"
COLORMAP_TURBO = "COLORMAP_TURBO"
COLORMAP_TWILIGHT = "COLORMAP_TWILIGHT"
COLORMAP_TWILIGHT_SHIFTED = "COLORMAP_TWILIGHT_SHIFTED"
COLORMAP_VIRIDIS = "COLORMAP_VIRIDIS"
COLORMAP_WINTER = "COLORMAP_WINTER"
